on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: aviate-labs/setup-dfx@main
        with:
          dfx-version: 0.7.2
      - run: go test -v ./...
