name: golangci-lint
on: push
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
      - run: go mod tidy
      - run: git diff --quiet go.mod go.sum
      - run: go install github.com/jdeflander/goarrange@v1.0.0
        working-directory: ${{ runner.temp }}
      - run: test -z "$(goarrange run -r -d)"
