on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: aviate-labs/setup-dfx@v0.2.2
        with:
          dfx-version: 0.8.0
          install-moc: true
      - run: go test -v ./...
