on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.10.0
      - run: go test -v ./...
